name: habit03
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  get: ^4.6.6
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  image_picker: ^1.1.2
  fl_chart: ^0.68.0
  cloud_firestore: ^5.2.1
  table_calendar: ^3.1.2
  file_picker: ^8.0.5
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.0
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  image_path: "assets/tracker.png"
  adaptive_icon_background: "#FFFFFF"  # For Android adaptive icons
  adaptive_icon_foreground: "assets/tracker.png"  # The actual app icon
